name: Generate Release Notes
description: Generate release notes based on git messages

on:
  workflow_call:
    outputs:
      notes-path:
        description: 'Release notes file'
        value: './RELEASE_NOTES.md'

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’¾ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ“ Generate Release Notes
        run: |
          echo "# Release Notes\n" > RELEASE_NOTES.md
          git log -1 --pretty=format:"%h - %s (%an)" >> RELEASE_NOTES.md

      - name: ğŸ–Šï¸ Commit Release Notes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add RELEASE_NOTES.md
          git commit -m "chore: update release notes [skip ci]" || echo "No changes to commit"
          git push

      - name: ğŸ“ Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: ./RELEASE_NOTES.md
