name: GitHub Release
description: Create a GitHub release when pushing a semantic versioned tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’¾ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸš€ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ”¹ Cache Dependencies
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: â™»ï¸ Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: ğŸ“ Upload Node Modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules
          retention-days: 5

  test:
    needs: setup
    uses: ./.github/workflows/test-coverage.yml

  changelog:
    uses: ./.github/workflows/generate-changelog.yml

  release-notes:
    uses: ./.github/workflows/generate-release-notes.yml

  release:
    needs: [changelog, release-notes]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’¾ Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dist

      # - name: ğŸ”¹ Cache Dependencies
      #   id: node-cache
      #   uses: actions/cache@v4
      #   with:
      #     path: node_modules
      #     key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # - name: â™»ï¸ Install Dependencies
      #   if: steps.node-cache.outputs.cache-hit != 'true'
      #   run: npm ci

      # - name: ğŸ§° Cache Build Output
      #   id: build-cache
      #   uses: actions/cache@v4
      #   with:
      #     path: lib
      #     key: build-${{ runner.os }}-${{ hashFiles('tsup.config.ts', 'src/**/*.ts') }}

      # - name: âš™ï¸ Compile SDK
      #   if: steps.build-cache.outputs.cache-hit != 'true'
      #   run: npm run build

      - uses: actions/download-artifact@v4
        with:
          name: changelog

      - uses: actions/download-artifact@v4
        with:
          name: release-notes

      - name: ğŸš€ Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./lib/**
          body_path: ./RELEASE_NOTES.md
